name: geocat_research
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.12
  - jupyterlab
  - jupyter-dash 
  - ipykernel
  - geocat-comp # mjo
  - geocat-viz # mjo
  - scipy
  - numpy
  - pandas
  - pyproj #  gc_* (great circle calculations)
  - uxarray # gc_* (great circle calculations)
  - xeofs # mjo
  - xrft # mjo: FFT
  #- iris # mjo: mjo_wavenumber
  - pip
  - pip:
      - ipywidgets
      - matplotlib
      - cmaps
