name: geocat_research
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.12
  - jupyterlab
  - jupyter-dash 
  - ipykernel
  - scipy
  - numpy
  - pandas
  - pyproj #  gc_* (great circle calculations)
  - uxarray # gc_* (great circle calculations)
  - pip
  - pip:
      - ipywidgets
      - matplotlib
      - cmaps
